### ISSUE TITLE
package path not exported

### ISSUE THREAD

**Issue by CritterCodes** [fionnachan/algorand-wallet-walletconnect-redux#2]
node:internal/modules/cjs/loader:598
      throw e;
      ^

Error [ERR_PACKAGE_PATH_NOT_EXPORTED]: Package subpath './lib/tokenize' is not defined by "exports" in C:\Users\jacob\OneDrive\Desktop\Projects\algorand-wallet-walletconnect-redux\node_modules\postcss-safe-parser\node_modules\postcss\package.json

**Comment by fionnachan** [comment]
Hi, this is unmaintained. Feel free to fork the repository and update relevant packages.
